In [406]:
import numpy as np
import pandas as pd

In [407]:
dat = pd.read_csv('regr.csv')
dat

x1   x2    t1   t2
0  1.5  2.1  10.0  5.0
1  3.2  0.7  14.5  7.3

In [408]:
X = dat[['x1','x2']].values
t = dat[['t1', 't2']].values
print(X.shape,t.shape)
W_1 = np.ones((3,4))
#W_1 = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])

(2, 2) (2, 2)


In [409]:
# Forward Pass #

def for1(X,W_1):
    X = np.concatenate((X, np.ones((X.shape[0], 1))), axis=1)
    return X@W_1

def act1(X): #this is an identity function
    return X
print("target matrix \n",t) #this is the target matrix

print("input layer \n",X) #this is the input layer

print("hidden layer 1 \n",act1(for1(X,W_1))) #this is the output of the first layer

def for2(Z,W_2):
    Z = np.concatenate((Z, np.ones((Z.shape[0], 1))), axis=1)
    return Z @ W_2

def act2(Z): #this is an identity function
    return Z

W_2 = np.ones((5,3))
#W_2 = np.array([[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1]])

print("hidden layer 2 \n",act2(for2(act1(for1(X,W_1)),W_2))) #this is the output of the second layer

def for3(P,W_3):
    P = np.concatenate((P, np.ones((P.shape[0], 1))), axis=1)
    return P @ W_3

def act3(P): #this is an identity function
    return P

W_3 = np.ones((4,2))

print("output layer \n",act3(for3(act2(for2(act1(for1(X,W_1)),W_2)),W_3))) #this is the output of the output layer

output1 = act3(for3(act2(for2(act1(for1(X,W_1)),W_2)),W_3))




target matrix 
 [[10.   5. ]
 [14.5  7.3]]
input layer 
 [[1.5 2.1]
 [3.2 0.7]]
hidden layer 1 
 [[4.6 4.6 4.6 4.6]
 [4.9 4.9 4.9 4.9]]
hidden layer 2 
 [[19.4 19.4 19.4]
 [20.6 20.6 20.6]]
output layer 
 [[59.2 59.2]
 [62.8 62.8]]


In [410]:
# Backward Pass #
#We will use the Sum of Squared Error (SSE) as the loss function

def delta_n(y,t):
    return y-t



def deltas(W_1,W_2,W_3,output,t):
    W_1_c = np.concatenate((W_1, np.ones((W_1.shape[0], 1))), axis=1)
    W_2_c = np.concatenate((W_2, np.ones((W_2.shape[0], 1))), axis=1)
    delta_4 = delta_n(output,t)
    delta_3 = delta_4 @ W_3.T
    delta_2 = delta_3 @ W_2_c.T
    delta_1 = delta_2 @ W_1_c.T
    return delta_1, delta_2, delta_3, delta_4

print("delta_1 \n",deltas(W_1,W_2,W_3,output1,t)[0])
print("delta_2 \n",deltas(W_1,W_2,W_3,output1,t)[1])
print("delta_3 \n",deltas(W_1,W_2,W_3,output1,t)[2])
print("delta_4 \n",deltas(W_1,W_2,W_3,output1,t)[3])

delta_1 = deltas(W_1,W_2,W_3,output1,t)[0]
delta_2 = deltas(W_1,W_2,W_3,output1,t)[1]
delta_3 = deltas(W_1,W_2,W_3,output1,t)[2]
delta_4 = deltas(W_1,W_2,W_3,output1,t)[3]

def deriv_E(W,delta):
    return W @ delta

#print(W_1_c.shape,delta_1.shape)
#print(W_2_c.shape,delta_2.shape)
#print(W_3.shape,delta_3.shape)
#print(W_1.shape,delta_1.shape)
#print(W_2.shape,delta_2.shape)

print("derivative of E with respect to W_1 \n",deriv_E(W_1[:,:-2],delta_1))
print("derivative of E with respect to W_2 \n",deriv_E(W_2[:,:-1],delta_2))
print("derivative of E with respect to W_3 \n",deriv_E(W_3,delta_3))

deriv_E_W1 = deriv_E(W_1[:,:-2],delta_1)
deriv_E_W2 = deriv_E(W_2[:,:-1],delta_2)
deriv_E_W3 = deriv_E(W_3,delta_3)


delta_1 
 [[2068. 2068. 2068.]
 [2076. 2076. 2076.]]
delta_2 
 [[413.6 413.6 413.6 413.6 413.6]
 [415.2 415.2 415.2 415.2 415.2]]
delta_3 
 [[103.4 103.4 103.4 103.4]
 [103.8 103.8 103.8 103.8]]
delta_4 
 [[49.2 54.2]
 [48.3 55.5]]
derivative of E with respect to W_1 
 [[4144. 4144. 4144.]
 [4144. 4144. 4144.]
 [4144. 4144. 4144.]]
derivative of E with respect to W_2 
 [[828.8 828.8 828.8 828.8 828.8]
 [828.8 828.8 828.8 828.8 828.8]
 [828.8 828.8 828.8 828.8 828.8]
 [828.8 828.8 828.8 828.8 828.8]
 [828.8 828.8 828.8 828.8 828.8]]
derivative of E with respect to W_3 
 [[207.2 207.2 207.2 207.2]
 [207.2 207.2 207.2 207.2]
 [207.2 207.2 207.2 207.2]
 [207.2 207.2 207.2 207.2]]


In [411]:
# Stocahstic Gradient Descent #

def SGD(W,deriv_E,eta,max_iter):
    for i in range(max_iter):
        W = W - (eta * deriv_E)
    return W

eta = 0.000001
max_iter = 1000
#epoch = 100

ones_2 = np.ones((5,2))
ones_3 = np.ones((4,2))
print(W_1.shape,ones_2.shape)
W_2_expand = np.concatenate((W_2, ones_2), axis=1)
W_3_expand = np.concatenate((W_3, ones_3), axis=1)
W_1_remove = W_1[:,:-1]

print(deriv_E_W1.shape,deriv_E_W2.shape,deriv_E_W3.shape)
print(W_1_remove.shape,W_2_expand.shape,W_3_expand.shape)

W_1_new = SGD(W_1_remove,deriv_E_W1,eta,max_iter)
W_2_new = SGD(W_2_expand,deriv_E_W2,eta,max_iter)
W_3_new = SGD(W_3_expand,deriv_E_W3,eta,max_iter)

W_1_new_adjusted = np.concatenate((W_1_new, np.ones((W_1_new.shape[0], 1))), axis=1)
W_2_new_adjusted = W_2_new[:,:-2]
W_3_new_adjusted = W_3_new[:,:-2]

print("W_1_new \n",W_1_new,W_1_new.shape)
print("W_2_new \n",W_2_new,W_2_new.shape)
print("W_3_new \n",W_3_new,W_3_new.shape)


(3, 4) (5, 2)
(3, 3) (5, 5) (4, 4)
(3, 3) (5, 5) (4, 4)
W_1_new 
 [[-3.144 -3.144 -3.144]
 [-3.144 -3.144 -3.144]
 [-3.144 -3.144 -3.144]] (3, 3)
W_2_new 
 [[0.1712 0.1712 0.1712 0.1712 0.1712]
 [0.1712 0.1712 0.1712 0.1712 0.1712]
 [0.1712 0.1712 0.1712 0.1712 0.1712]
 [0.1712 0.1712 0.1712 0.1712 0.1712]
 [0.1712 0.1712 0.1712 0.1712 0.1712]] (5, 5)
W_3_new 
 [[0.7928 0.7928 0.7928 0.7928]
 [0.7928 0.7928 0.7928 0.7928]
 [0.7928 0.7928 0.7928 0.7928]
 [0.7928 0.7928 0.7928 0.7928]] (4, 4)


In [412]:
# Forward Prop 2 #

print(act3(for3(act2(for2(act1(for1(X,W_1_new_adjusted)),W_2_new_adjusted)),W_3_new_adjusted))) #this is the output of the output layer

# Backward Prop 2 #
output2 = act3(for3(act2(for2(act1(for1(X,W_1_new_adjusted)),W_2_new_adjusted)),W_3_new_adjusted))

print("delta_1 \n",deltas(W_1_new_adjusted,W_2_new_adjusted,W_3_new_adjusted,output2,t)[0])
print("delta_2 \n",deltas(W_1_new_adjusted,W_2_new_adjusted,W_3_new_adjusted,output2,t)[1])
print("delta_3 \n",deltas(W_1_new_adjusted,W_2_new_adjusted,W_3_new_adjusted,output2,t)[2])
print("delta_4 \n",deltas(W_1_new_adjusted,W_2_new_adjusted,W_3_new_adjusted,output2,t)[3])

delta_1_new = deltas(W_1_new_adjusted,W_2_new_adjusted,W_3_new_adjusted,output2,t)[0]
delta_2_new = deltas(W_1_new_adjusted,W_2_new_adjusted,W_3_new_adjusted,output2,t)[1]
delta_3_new = deltas(W_1_new_adjusted,W_2_new_adjusted,W_3_new_adjusted,output2,t)[2]
delta_4_new = deltas(W_1_new_adjusted,W_2_new_adjusted,W_3_new_adjusted,output2,t)[3]

deriv_E_W1_new = deriv_E(W_1_new_adjusted[:,:-2],delta_1_new)
deriv_E_W2_new = deriv_E(W_2_new_adjusted[:,:-1],delta_2_new)
deriv_E_W3_new = deriv_E(W_3_new_adjusted,delta_3_new)

print("derivative of E with respect to W_1 \n",deriv_E_W1_new)
print("derivative of E with respect to W_2 \n",deriv_E_W2_new)
print("derivative of E with respect to W_3 \n",deriv_E_W3_new)




[[-14.59347069 -14.59347069]
 [-15.62347848 -15.62347848]]
delta_1 
 [[394.07093318 394.07093318 394.07093318]
 [473.08691613 473.08691613 473.08691613]]
delta_2 
 [[-53.02353783 -53.02353783 -53.02353783 -53.02353783 -53.02353783]
 [-63.65539776 -63.65539776 -63.65539776 -63.65539776 -63.65539776]]
delta_3 
 [[-35.03140713 -35.03140713 -35.03140713 -35.03140713]
 [-42.05562748 -42.05562748 -42.05562748 -42.05562748]]
delta_4 
 [[-24.59347069 -19.59347069]
 [-30.12347848 -22.92347848]]
derivative of E with respect to W_1 
 [[-2726.34427826 -2726.34427826 -2726.34427826]
 [-2726.34427826 -2726.34427826 -2726.34427826]
 [-2726.34427826 -2726.34427826 -2726.34427826]]
derivative of E with respect to W_2 
 [[-19.97543377 -19.97543377 -19.97543377 -19.97543377 -19.97543377]
 [-19.97543377 -19.97543377 -19.97543377 -19.97543377 -19.97543377]
 [-19.97543377 -19.97543377 -19.97543377 -19.97543377 -19.97543377]
 [-19.97543377 -19.97543377 -19.97543377 -19.97543377 -19.97543377]
 [-19.97543377 -